spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ms-user-eureka
      password: xHdHnR3dx70F1Gu

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF