spring:
  application:
    name: mscloudgateway
  cloud:
    loud:
      gateway:
        discovery:
          locator:
            enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7000/realms/msrealm
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-user-eureka:xHdHnR3dx70F1Gu@localhost:8761/eureka